package com.portfolio.backend;

import com.portfolio.backend.dto.ProjectDTO;
import com.portfolio.backend.exception.ResourceNotFoundException;
import com.portfolio.backend.service.ProjectService;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@ActiveProfiles("test")
@Transactional
public class ProjectServiceTests {

    @Autowired
    private ProjectService projectService;

    @Test
    @DisplayName("1. Test Create Project")
    void testCreateProject() {
        ProjectDTO newProject = ProjectDTO.builder()
                .title("Distributed Event Bus")
                .slug("distributed-event-bus-test")
                .category("Java / Spring Boot")
                .tagline("High throughput Kafka messaging system")
                .description("Test description for distributed event bus")
                .longDescription("Longer detailed description with architecture")
                .image("https://example.com/image.png")
                .githubUrl("https://github.com/alexandervance/event-bus")
                .liveUrl("https://demo.example.com")
                .featured(true)
                .displayOrder(10)
                .technologies(new HashSet<>(Arrays.asList("Java", "Kafka", "Spring Boot", "Docker")))
                .features(Arrays.asList("High availability", "Zero message loss"))
                .build();

        ProjectDTO created = projectService.createProject(newProject);

        assertNotNull(created.getId(), "Project ID should be generated by MySQL/JPA");
        assertEquals("Distributed Event Bus", created.getTitle());
        assertEquals("distributed-event-bus-test", created.getSlug());
        assertTrue(created.getTechnologies().contains("Kafka"));
        assertEquals(2, created.getFeatures().size());
    }

    @Test
    @DisplayName("2. Test Read Project")
    void testReadProject() {
        ProjectDTO newProject = ProjectDTO.builder()
                .title("Read Test System")
                .slug("read-test-system")
                .category("Microservices / Cloud")
                .tagline("Test tagline")
                .description("Test description")
                .githubUrl("https://github.com/example/read-test")
                .technologies(new HashSet<>(Arrays.asList("Java", "AWS")))
                .features(Arrays.asList("Feature A"))
                .build();

        ProjectDTO created = projectService.createProject(newProject);
        assertNotNull(created.getId());

        // Read by ID
        ProjectDTO retrievedById = projectService.getProjectById(created.getId());
        assertNotNull(retrievedById);
        assertEquals("Read Test System", retrievedById.getTitle());

        // Read by Slug
        ProjectDTO retrievedBySlug = projectService.getProjectBySlug("read-test-system");
        assertNotNull(retrievedBySlug);
        assertEquals(created.getId(), retrievedBySlug.getId());

        // Read all
        List<ProjectDTO> allProjects = projectService.getAllProjects();
        assertFalse(allProjects.isEmpty());
    }

    @Test
    @DisplayName("3. Test Update Project")
    void testUpdateProject() {
        ProjectDTO newProject = ProjectDTO.builder()
                .title("Initial Project Name")
                .slug("initial-project-slug")
                .category("Java / Spring Boot")
                .tagline("Initial Tagline")
                .description("Initial Description")
                .githubUrl("https://github.com/example/initial")
                .technologies(new HashSet<>(Arrays.asList("Java")))
                .features(Arrays.asList("Feature 1"))
                .build();

        ProjectDTO created = projectService.createProject(newProject);

        // Update fields
        created.setTitle("Updated Project Name");
        created.setTagline("Updated Tagline");
        created.getTechnologies().add("Spring Security");

        ProjectDTO updated = projectService.updateProject(created.getId(), created);

        assertEquals("Updated Project Name", updated.getTitle());
        assertEquals("Updated Tagline", updated.getTagline());
        assertTrue(updated.getTechnologies().contains("Spring Security"));
    }

    @Test
    @DisplayName("4. Test Delete Project")
    void testDeleteProject() {
        ProjectDTO newProject = ProjectDTO.builder()
                .title("To Be Deleted Project")
                .slug("to-be-deleted-slug")
                .category("Systems & Tools")
                .tagline("Ephemeral project")
                .description("Ephemeral description")
                .githubUrl("https://github.com/example/ephemeral")
                .technologies(new HashSet<>(Arrays.asList("Python")))
                .build();

        ProjectDTO created = projectService.createProject(newProject);
        Long id = created.getId();

        // Delete
        projectService.deleteProject(id);

        // Verify resource not found
        assertThrows(ResourceNotFoundException.class, () -> projectService.getProjectById(id));
    }
}
